version: "3.9"
services:
  consumer-service:
    build:
      context: ./consumer-service
      dockerfile: Dockerfile
    env_file: consumer-service/.env
    tty: true
    image: consumer-service:latest
    container_name: consumer-service
    volumes:
      - ./consumer-service:/usr/src/consumer-service
    ports:
      - 3000:3000
    depends_on:
      - kafka

  producer-service:
    build:
      context: ./producer-service
      dockerfile: Dockerfile
    env_file: producer-service/.env
    tty: true
    image: producer-service:latest
    container_name: producer-service
    volumes:
      - ./producer-service:/usr/src/producer-service
    ports:
      - 5000:5000
    depends_on:
      - kafka

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    env_file: .env.docker-compose
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    env_file: .env.docker-compose
    ports:
      - "2181:2181"

  mongodb:
    image: mongo:latest
    env_file: .env.docker-compose
    ports:
      - 27017:27017
